name: build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: self-hosted
        
        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8.0.401

            - name: Install dependencies
              run: dotnet restore
              working-directory: .

            - name: Build
              run: dotnet build --configuration Release --no-restore
              working-directory: .

            - name: Test
              run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
              working-directory: .

            - name: Publish code coverage reports to codecove.io
              uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./**/coverage.cobertura.xml
                  fail_ci_if_error: true

